# Site settings
baseurl = "https://example.org/"
languageCode = "en-us"
title = "Hugo Freelancer Theme"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Mr. Hugo"
    description = "My awesome description"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "your@email.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Mr. Hugo's Portfolio"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Mr. Hugo"
        subtitle = "Blogger - Programmer - Gopher"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization."
        right = "Whether you're a student looking to showcase your work, a professional looking to attract clients, or a graphic artist looking to share your projects, this template is the perfect starting point!"

        [params.about.button]
            text = "Download theme"
            link = "//github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip"
            icon = "download"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["3481 Melrose Place", "Beverly Hills, CA 90210"]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/spf13/hugo"

            [[params.footer.social.networks]]
                icon = "fa-stack-overflow"
                link=  "//stackoverflow.com/questions/tagged/hugo"


        [params.footer.credits]
            title = "About Freelancer"
            text = "Freelance is a free to use, open source Bootstrap theme created by [Start Bootstrap](//startbootstrap.com)."
